import path from 'path';
import { defineConfig, loadEnv } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, '.', '');

  return {
    base: '/',
    appType: 'mpa',
    server: {
      port: 3000,
      host: '0.0.0.0',
    },
    plugins: [react()],
    optimizeDeps: {
      include: ['lucide-react'],
    },
    define: {
      'process.env.API_KEY': JSON.stringify(env.GEMINI_API_KEY),
      'process.env.GEMINI_API_KEY': JSON.stringify(env.GEMINI_API_KEY),
    },
    resolve: {
      alias: {
        '@': path.resolve(__dirname, '.'),
      },
    },
    build: {
      rollupOptions: {
        input: {
          main: path.resolve(__dirname, 'index.html'),
          servicios: path.resolve(__dirname, 'servicios/index.html'),
          contacto: path.resolve(__dirname, 'contacto/index.html'),
          faq: path.resolve(__dirname, 'faq/index.html'),
          automatizacionProcesos: path.resolve(__dirname, 'automatizacion-procesos/index.html'),
          iaEmpresas: path.resolve(__dirname, 'ia-empresas/index.html'),
          optimizacionOperativa: path.resolve(__dirname, 'optimizacion-operativa-pymes/index.html'),
          automatizacionWhatsApp: path.resolve(__dirname, 'automatizacion-whatsapp-empresas/index.html'),
          automatizacionSeguimiento: path.resolve(__dirname, 'automatizacion-seguimiento-clientes/index.html'),
          crmPymesSeguimientoClientes: path.resolve(__dirname, 'crm-pymes-seguimiento-clientes/index.html'),
          automatizacionClinicas: path.resolve(__dirname, 'automatizacion-clinicas/index.html'),
          galiciaNew: path.resolve(__dirname, 'automatizacion-empresas-galicia/index.html'),
          blog: path.resolve(__dirname, 'blog/index.html'),
          blogPost1: path.resolve(__dirname, 'blog/automatizaciones-que-recuperan-tiempo-pymes/index.html'),
          blogPost2: path.resolve(__dirname, 'blog/por-que-las-pymes-pierden-clientes-antes-de-firmar/index.html'),
          blogPost3: path.resolve(__dirname, 'blog/dejar-de-gestionar-whatsapp-empresa-a-mano/index.html'),
          blogPost4: path.resolve(__dirname, 'blog/como-saber-que-proceso-automatizar-primero/index.html'),
          blogPost5: path.resolve(__dirname, 'blog/reducir-ausencias-clinicas-recordatorios-automaticos/index.html'),
          blogPost6: path.resolve(__dirname, 'blog/tareas-manuales-que-frenan-tu-negocio/index.html'),
          blogPost7: path.resolve(__dirname, 'blog/seguimiento-leads-pymes-cuando-insistir/index.html'),
          blogPost8: path.resolve(__dirname, 'blog/whatsapp-business-app-vs-api-pymes/index.html'),
          blogPost9: path.resolve(__dirname, 'blog/reactivar-leads-frios-sin-perseguir/index.html'),
          blogPost10: path.resolve(__dirname, 'blog/confirmacion-citas-whatsapp-clinicas/index.html'),
          blogPost11: path.resolve(__dirname, 'blog/crm-no-falla-falla-el-proceso/index.html'),
          blogPost12: path.resolve(__dirname, 'blog/herramientas-desconectadas-equipo-va-tarde/index.html'),
          blogPost13: path.resolve(__dirname, 'blog/todo-depende-de-una-sola-persona/index.html'),
          blogPost14: path.resolve(__dirname, 'blog/ia-para-pymes-cuando-tiene-sentido/index.html'),
          blogPost15: path.resolve(__dirname, 'blog/asistente-ia-atencion-cliente-pymes/index.html'),
          blogPost16: path.resolve(__dirname, 'blog/conectar-whatsapp-crm-sin-crear-mas-trabajo/index.html'),
          blogPost17: path.resolve(__dirname, 'blog/automatizar-presupuestos-seguimiento-pymes/index.html'),
          blogPost18: path.resolve(__dirname, 'blog/automatizacion-empresas-galicia-procesos-retorno/index.html'),
          blogPost19: path.resolve(__dirname, 'blog/seguimiento-pacientes-clinicas-antes-despues-cita/index.html'),
          blogPost20: path.resolve(__dirname, 'blog/automatizacion-academias-matriculas-seguimiento/index.html'),
          blogPost21: path.resolve(__dirname, 'blog/automatizacion-inmobiliarias-leads-portales-whatsapp/index.html'),
          blogPost22: path.resolve(__dirname, 'blog/automatizacion-asesorias-vencimientos-documentos-clientes/index.html'),
          blogPost23: path.resolve(__dirname, 'blog/documentar-procesos-pyme-sin-complicarse/index.html'),
          blogPost24: path.resolve(__dirname, 'blog/errores-automatizar-empresa-primera-vez/index.html'),
          blogPost25: path.resolve(__dirname, 'blog/mensajes-automaticos-clientes-cuando-ayudan-molestan/index.html'),
          blogPost26: path.resolve(__dirname, 'blog/automatizacion-gimnasios-renovaciones-seguimiento-socios/index.html'),
          blogPost27: path.resolve(__dirname, 'blog/automatizacion-reformas-instaladoras-presupuestos-visitas/index.html'),
          blogPost28: path.resolve(__dirname, 'blog/automatizacion-procesos-pontevedra-pymes-servicios/index.html'),
          blogPost29: path.resolve(__dirname, 'blog/cuanto-cuesta-automatizar-procesos-pyme/index.html'),
          blogPost30: path.resolve(__dirname, 'blog/diferencia-digitalizacion-automatizacion-ia-pymes/index.html'),
          blogPost31: path.resolve(__dirname, 'blog/integrar-calendario-email-crm-pymes/index.html'),
          blogPost32: path.resolve(__dirname, 'blog/automatizacion-clinicas-esteticas-primera-consulta-seguimiento/index.html'),
          blogPost33: path.resolve(__dirname, 'blog/automatizacion-despachos-abogados-expedientes-clientes/index.html'),
          blogPost34: path.resolve(__dirname, 'blog/onboarding-clientes-pymes-servicios-automatizado/index.html'),
          blogPost35: path.resolve(__dirname, 'blog/automatizar-cobros-recordatorios-pago-pymes/index.html'),
          blogPost36: path.resolve(__dirname, 'blog/preparar-datos-empresa-automatizar-ia/index.html'),
          blogPost37: path.resolve(__dirname, 'blog/automatizacion-empresas-vigo-pymes-servicios/index.html'),
          blogPost38: path.resolve(__dirname, 'blog/automatizacion-con-ia-empresas-pymes-servicios/index.html'),
          blogPost39: path.resolve(__dirname, 'blog/automatizacion-procesos-con-ia-pymes/index.html'),
          blogPost40: path.resolve(__dirname, 'blog/agencia-automatizacion-ia-como-elegir/index.html'),
          blogPost41: path.resolve(__dirname, 'blog/servicios-consultoria-automatizacion-ia-pymes/index.html'),
          blogPost42: path.resolve(__dirname, 'blog/herramientas-automatizacion-ia-pymes/index.html'),
          blogPost43: path.resolve(__dirname, 'blog/automatizacion-no-code-flujos-ia-pymes/index.html'),
          blogPost44: path.resolve(__dirname, 'blog/gestion-documental-ia-automatizacion-pymes/index.html'),
          blogPost45: path.resolve(__dirname, 'blog/chatbot-ia-atencion-cliente-pymes/index.html'),
          blogPost46: path.resolve(__dirname, 'blog/automatizacion-inteligente-tareas-repetitivas/index.html'),
          blogPost47: path.resolve(__dirname, 'blog/software-rpa-ia-pymes-antes-comprar/index.html'),
          blogPost48: path.resolve(__dirname, 'blog/que-es-automatizacion-con-ia-pymes/index.html'),
          blogPost49: path.resolve(__dirname, 'blog/como-funciona-automatizacion-con-ia-empresa/index.html'),
          blogPost50: path.resolve(__dirname, 'blog/sistema-automatizado-ia-pyme/index.html'),
          blogPost51: path.resolve(__dirname, 'blog/tipos-automatizacion-empresa-reglas-ia-rpa/index.html'),
          blogPost52: path.resolve(__dirname, 'blog/ia-automatizacion-diferencias-trabajan-juntas/index.html'),
          blogPost53: path.resolve(__dirname, 'blog/ejemplos-automatizacion-ia-atencion-ventas-administracion/index.html'),
          blogPost54: path.resolve(__dirname, 'blog/aplicaciones-ia-pymes-servicios/index.html'),
          blogPost55: path.resolve(__dirname, 'blog/tipos-ia-pymes-servicios/index.html'),
          blogPost56: path.resolve(__dirname, 'blog/ia-mas-usadas-empresas-pymes/index.html'),
          blogPost57: path.resolve(__dirname, 'blog/chatgpt-vs-otras-ia-empresa/index.html'),
        },
      },
    },
  };
});
